theme: minimal-mistakes-jekyll

title: Données structurées
description: Contenus pour le cours « Documents structurés et écriture numérique » du master Plurital.

baseurl: https://loicgrobol.github.io/structured-data

exclude:
  - "*.py.md"

keep_files:
  - "*.py.html"
  - "pdf_slides/*"

plugins:
  - jekyll-default-layout

