theme: minimal-mistakes-jekyll

title: Données structurées — M2 PluriTAL
description: Contenus pour le cours « Documents structurés et écriture numérique » du master Plurital.
name: Loïc Grobol

baseurl: "/structured-data"
repository: "loicgrobol/structured-data"

atom_feed:
  hide: true


exclude:
  - "*.py.md"

keep_files:
  - "*.py.html"
  - "pdf_slides/*"

plugins:
  - jekyll-default-layout

